# Generated by Django 5.1 on 2025-10-26 10:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Naam')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Beschrijving')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Aangemaakt op')),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categorieën',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_participants', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Aantal deelnemers')),
                ('first_name', models.CharField(max_length=100, verbose_name='Voornaam')),
                ('last_name', models.CharField(max_length=100, verbose_name='Achternaam')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefoonnummer')),
                ('participants_details', models.JSONField(blank=True, help_text='Extra informatie over deelnemers', null=True, verbose_name='Deelnemers details')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Totaalprijs (€)')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Onbetaald'), ('paid', 'Betaald'), ('refunded', 'Terugbetaald')], default='unpaid', max_length=20, verbose_name='Betalingsstatus')),
                ('status', models.CharField(choices=[('pending', 'In afwachting'), ('confirmed', 'Bevestigd'), ('cancelled', 'Geannuleerd'), ('completed', 'Voltooid')], default='pending', max_length=20, verbose_name='Boekingsstatus')),
                ('notes', models.TextField(blank=True, verbose_name='Opmerkingen')),
                ('dietary_requirements', models.TextField(blank=True, verbose_name='Dieetwensen')),
                ('booking_reference', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Boekingsreferentie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Geboekt op')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geüpdatet op')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bevestigd op')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Geannuleerd op')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Gebruiker')),
            ],
            options={
                'verbose_name': 'Boeking',
                'verbose_name_plural': 'Boekingen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Beschrijving')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Korte beschrijving')),
                ('start_datetime', models.DateTimeField(verbose_name='Start datum & tijd')),
                ('end_datetime', models.DateTimeField(verbose_name='Eind datum & tijd')),
                ('duration_hours', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0.5)], verbose_name='Duur (uren)')),
                ('location', models.CharField(max_length=200, verbose_name='Locatie')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Adres')),
                ('city', models.CharField(default='Gent', max_length=100, verbose_name='Stad')),
                ('max_participants', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Maximum aantal deelnemers')),
                ('min_participants', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minimum aantal deelnemers')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prijs per persoon (€)')),
                ('materials_included', models.BooleanField(default=True, verbose_name='Materialen inbegrepen')),
                ('requirements', models.TextField(blank=True, help_text='Bijv. ervaring, leeftijd, etc.', verbose_name='Vereisten')),
                ('what_to_bring', models.TextField(blank=True, verbose_name='Wat meenemen')),
                ('image', models.ImageField(blank=True, null=True, upload_to='workshops/', verbose_name='Afbeelding')),
                ('status', models.CharField(choices=[('upcoming', 'Binnenkort'), ('active', 'Actief'), ('full', 'Volzet'), ('cancelled', 'Geannuleerd'), ('completed', 'Afgelopen')], default='upcoming', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actief')),
                ('featured', models.BooleanField(default=False, verbose_name='Uitgelicht')),
                ('instructor_name', models.CharField(max_length=200, verbose_name='Instructeur naam')),
                ('instructor_bio', models.TextField(blank=True, verbose_name='Instructeur bio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Aangemaakt op')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geüpdatet op')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshops', to='workshops.category', verbose_name='Categorie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workshops', to=settings.AUTH_USER_MODEL, verbose_name='Aangemaakt door')),
            ],
            options={
                'verbose_name': 'Workshop',
                'verbose_name_plural': 'Workshops',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Beoordeling')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('comment', models.TextField(verbose_name='Commentaar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Aangemaakt op')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geüpdatet op')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Goedgekeurd')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='workshops.booking', verbose_name='Boeking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Gebruiker')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='workshops.workshop', verbose_name='Workshop')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='workshops.workshop', verbose_name='Workshop'),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['start_datetime'], name='workshops_w_start_d_caea3c_idx'),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['status'], name='workshops_w_status_e352fa_idx'),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['is_active'], name='workshops_w_is_acti_ad378a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('workshop', 'user')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_reference'], name='workshops_b_booking_01160d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='workshops_b_status_1c2b18_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='workshops_b_created_2e8252_idx'),
        ),
    ]
