# Generated by Django 5.1 on 2025-10-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='created_by',
        ),
    ]
