# Generated by Django 5.1 on 2025-10-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_remove_workshop_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='bi-lightbulb', help_text='Bootstrap icon class (bijv. bi-cpu, bi-gear, bi-rocket). Zie https://icons.getbootstrap.com/', max_length=50, verbose_name='Bootstrap Icon'),
        ),
    ]
