# Generated by Django 5.1 on 2025-10-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email adres')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Voornaam')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Achternaam')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actief')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Bevestigd')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Ingeschreven op')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Uitgeschreven op')),
                ('interests', models.JSONField(blank=True, help_text='Categorieën waar de subscriber in geïnteresseerd is', null=True, verbose_name='Interesses')),
            ],
            options={
                'verbose_name': 'Nieuwsbrief Inschrijving',
                'verbose_name_plural': 'Nieuwsbrief Inschrijvingen',
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['email'], name='workshops_n_email_44c0bc_idx'), models.Index(fields=['is_active'], name='workshops_n_is_acti_e448d9_idx')],
            },
        ),
    ]
