# Generated by Django 5.1 on 2025-11-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0005_webinar_conversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='InhouseTrainingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(default='Op zoek naar opleidingen op maat voor jouw team?', help_text='Titel die getoond wordt op de homepage', max_length=200, verbose_name='Banner Titel')),
                ('banner_description', models.TextField(default='Ontdek onze inhouse trainingen: volledig aangepast aan de behoeften van jouw organisatie. Van AI-geletterdheid tot geavanceerde workflow automation - wij brengen de kennis naar jullie kantoor of online omgeving.', help_text='Korte beschrijving op de homepage', verbose_name='Banner Beschrijving')),
                ('banner_button_text', models.CharField(default='Ontdek Inhouse Opleidingen', max_length=50, verbose_name='Banner Knop Tekst')),
                ('page_title', models.CharField(default='Inhouse Trainingen op Maat', max_length=200, verbose_name='Pagina Titel')),
                ('intro_text', models.TextField(default='Bij Narhval Learning begrijpen we dat elke organisatie uniek is. Daarom bieden wij volledig op maat gemaakte AI-opleidingen aan die perfect aansluiten bij jouw bedrijfsdoelen en uitdagingen.', verbose_name='Introductie Tekst')),
                ('benefits_title', models.CharField(default='Waarom kiezen voor inhouse training?', max_length=200, verbose_name='Voordelen Titel')),
                ('benefits', models.JSONField(blank=True, default=list, help_text='Lijst van voordelen (wordt automatisch aangemaakt bij eerste save)', verbose_name='Voordelen Lijst')),
                ('process_title', models.CharField(default='Hoe werken we samen?', max_length=200, verbose_name='Proces Titel')),
                ('process_description', models.TextField(default='We volgen een gestructureerde aanpak om ervoor te zorgen dat de training perfect aansluit bij jullie behoeften:', verbose_name='Proces Beschrijving')),
                ('process_steps', models.JSONField(blank=True, default=list, help_text='Lijst van processtappen (wordt automatisch aangemaakt bij eerste save)', verbose_name='Proces Stappen')),
                ('topics_title', models.CharField(default='Mogelijke trainingsonderwerpen', max_length=200, verbose_name='Onderwerpen Titel')),
                ('topics_description', models.TextField(default='Wij kunnen trainingen verzorgen over diverse AI-gerelateerde onderwerpen, waaronder:', verbose_name='Onderwerpen Beschrijving')),
                ('cta_title', models.CharField(default='Klaar om te starten?', max_length=200, verbose_name='CTA Titel')),
                ('cta_description', models.TextField(default='Neem contact met ons op voor een vrijblijvend gesprek over de mogelijkheden voor jouw organisatie.', verbose_name='CTA Beschrijving')),
                ('cta_button_text', models.CharField(default='Neem Contact Op', max_length=50, verbose_name='CTA Knop Tekst')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actief')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Laatst gewijzigd')),
            ],
            options={
                'verbose_name': 'Inhouse Training Pagina',
                'verbose_name_plural': 'Inhouse Training Pagina',
            },
        ),
    ]
